#!/bin/bash
#
# chkconfig: 35 90 12
# description: ZabbixDBA monitoring service

source /etc/init.d/functions
source /opt/ZabbixDBA/settings.sh

if [[ ! ${RUN_AS} ]]; then
    RUN_AS=root
fi

start() {
    if [[ -e "$LOCKFILE" ]]; then
        echo 'Service is already running with pid' $(cat "$PIDFILE")
    else
        echo -n 'Starting ZabbixDBA service: '
        su - "${RUN_AS}" -c "$PERL_BIN /opt/ZabbixDBA/ZabbixDBA.pl '$CONFIG'" &
        sleep 1
        if ! ps -p $! > /dev/null; then
            failure $"ZabbixDBA failed to start"
            exit 1
        fi
        echo $! > "$PIDFILE"
        touch "$LOCKFILE"
        success $"ZabbixDBA started"
        echo
    fi
}

stop() {
    if [[ -e "$LOCKFILE" ]]; then
        echo -n 'Stopping ZabbixDBA service: '
        xargs kill -s INT < "$PIDFILE"
        if [[ $? != 0 ]]; then
            failure $"ZabbixDBA failed to stop"
        else
            success $"ZabbixDBA stopped"
        fi
        rm -f "$LOCKFILE" "$PIDFILE"
        echo
    else
        echo 'Service is not running'
    fi  
}

status() {
    if [[ -e "$LOCKFILE" ]]; then
        echo 'Service is running with pid' $(cat "$PIDFILE")
    else
        echo 'Service is not running'
    fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart|reload)
        stop
        sleep 3
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0